module.exports = {
	// SYMBOL STATUS (status)
	symbolStatus: {
		PRE_TRADING: 'PRE_TRADING',
		TRADING: 'TRADING',
		POST_TRADING: 'POST_TRADING',
		END_OF_DAY: 'END_OF_DAY',
		HALT: 'HALT',
		AUCTION_MATCH: 'AUCTION_MATCH',
		BREAK: 'BREAK',
	},
	// SYMBOL TYPE
	symbolType: {
		SPOT: 'SPOT'
	},
	// ORDER STATUS (status)
	orderStatus: {
		NEW: 'NEW',
		PARTIALLY_FILLED: 'PARTIALLY_FILLED',
		FILLED: 'FILLED',
		CANCELED: 'CANCELED',
		PENDING_CANCEL: 'PENDING_CANCEL',
		REJECTED: 'REJECTED',
		EXPIRED: 'EXPIRED'
	},
	// ORDER TYPES (orderTypes, type)
	orderTypes: {
		LIMIT: 'LIMIT',
		MARKET: 'MARKET',
		STOP_LOSS: 'STOP_LOSS',
		STOP_LOSS_LIMIT: 'STOP_LOSS_LIMIT',
		TAKE_PROFIT: 'TAKE_PROFIT',
		TAKE_PROFIT_LIMIT: 'TAKE_PROFIT_LIMIT',
		LIMIT_MAKER: 'LIMIT_MAKER'
	},
	// ORDER SIDE
	orderSide: {
		BUY: 'BUY',
		SELL: 'SELL'
	},
	// TIME IN FORCE (timeInForce)
	timeInForce: {
		GTC: 'GTC',
		IOC: 'IOC',
		FOK: 'FOK'
	},
	// CANDLESTICK INTERVALS
	candleStickIntervals: {
		ONE_MIN: '1m',
		THREE_MIN: '3m',
		FIVE_MIN: '5m',
		FIFTEEN_MIN: '15m',
		THIRTY_MIN: '30m',
		ONE_HOUR: '1h',
		TWO_HOURS: '2h',
		FOUR_HOURS: '4h',
		SIX_HOURS: '6h',
		EIGHT_HOURS: '8h',
		TWELVE_HOURS: '12h',
		ONE_DAY: '1d',
		THREE_DAYS: '3d',
		ONE_WEEK: '1w',
		ONE_MONTH: '1M'
	},
	// RATE LIMITERS (rateLimitType)
	rateLimitType: {
		REQUEST_WEIGHT: 'REQUEST_WEIGHT',
		ORDERS: 'ORDERS',
		RAW_REQUESTS: 'RAW_REQUESTS'
	},
	// RATE LIMIT INTERVALS (interval)
	rateLimitIntervals: {
		SECOND: 'SECOND',
		MINUTE: 'MINUTE',
		DAY: 'DAY'
	}
}
